# Requirement
# 1. Repo kalian harus ada Dockerfile
# 2. Harus punya akun docker hub

# Event:
# on push master/main

# Steps:
# 1. Checkout repo
# 2. Login ke docker hub
# 3. Docker build
# 4. Docker push

# Twist:
# 1. Jangan nge push password ke github
#    Perlu pakai env dan secrets

on:
  push:
    branches:
      - main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
