# Event:
# on pull request

# Jobs:
# 1. lint
# 2. test

# steps lint:
# 1. Checkout repo
# 2. Setup go
# 3. Run lint. `make lint` / `go fmt ./...`

# steps test:
# 1. Checkout repo
# 2. Setup go
# 3. Run test. `make test`

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - run: make lint
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - run: make test

# on: pull_request
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: action/checkout@v2
#       - uses: action/go-setup@v2
#         with:
#           go-version: ''
#       - run: |
#           go fmt ./...
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: action/checkout@v2
#       - uses: action/go-setup@v2
#         with:
#           go-version: ''
#       - run: |
#           go test

